import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const require=createRequire(import.meta.url);
const { chromium }=require('playwright-core');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox']});
const errors=[];
const context=await browser.newContext({viewport:{width:1440,height:1050},acceptDownloads:true});
await context.route('https://fonts.googleapis.com/**',r=>r.abort());
await context.addInitScript(()=>{
  window.registeredTools={};
  Object.defineProperty(document,'modelContext',{value:{registerTool(tool){window.registeredTools[tool.name]=tool;}}});
});
const page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173/');
await page.locator('#nav-editor').click();
await page.screenshot({path:'/tmp/angle-review-input.png',fullPage:true});
assert.equal(await page.locator('#draft').inputValue().then(v=>v.includes('50%')),true);
await page.locator('#run-review').click();
await page.locator('#result-view').waitFor({state:'visible'});
assert.equal(await page.locator('#total-count').textContent(),'4');
const card=page.locator('.finding').filter({hasText:'関連する取材発言と数値が異なります'});
await card.getByRole('button',{name:'修正を採用',exact:true}).click();
assert.equal(await page.locator('#accepted-count').textContent(),'1');
await page.locator('#show-revised').click();
assert.ok((await page.locator('#article-content').textContent()).includes('30%削減'));
assert.ok(!(await page.locator('#article-content').textContent()).includes('50%削減'));
await page.locator('#export-button').click();
assert.ok((await page.locator('#export-text').inputValue()).includes('30%削減'));
const downloadPromise=page.waitForEvent('download');
await page.locator('#download-draft').click();
const download=await downloadPromise;
const content=await fs.readFile(await download.path(),'utf8');
assert.ok(content.includes('30%削減'));
await page.locator('[data-close="export-dialog"]').click();
await card.getByRole('button',{name:'採用を取り消す',exact:true}).click();
assert.equal(await page.locator('#accepted-count').textContent(),'0');
const quoteCard=page.locator('.finding').filter({hasText:'引用文が文字起こしと一致しません'});
await quoteCard.getByRole('button',{name:'修正を採用',exact:true}).click();
assert.ok((await page.locator('#notice').textContent()).includes('入力してください'));
await quoteCard.getByRole('button',{name:'却下',exact:true}).click();
assert.equal(await page.locator('#pending-count').textContent(),'3');
await page.locator('#filter').selectOption('dismissed');
assert.equal(await page.locator('.finding').count(),1);
await page.locator('#filter').selectOption('all');
await page.screenshot({path:'/tmp/angle-review-results.png',fullPage:true});

const toolNames=await page.evaluate(()=>Object.keys(window.registeredTools));
assert.deepEqual(toolNames.sort(),['read_editorial_review','read_production_workflow','review_sample_article']);
const invalid=await page.evaluate(async()=>{try{await window.registeredTools.review_sample_article.execute({replaceConfirmed:false});return false;}catch{return true;}});
assert.equal(invalid,true);
const toolResult=await page.evaluate(()=>window.registeredTools.review_sample_article.execute({replaceConfirmed:true}));
assert.equal(toolResult.count,4);
const readBack=await page.evaluate(()=>window.registeredTools.read_editorial_review.execute({}));
assert.equal(readBack.findings.length,4);

// Mock the same-origin gateway contract. Real paid model calls are not made.
// The local development server has no operator key, so report a configured server and re-run discovery.
await page.route('**/api/{status,connection}',r=>r.fulfill({json:{configured:true,connection:'ready',defaultModel:'openai/gpt-4.1-mini'}}));
await page.evaluate(()=>import('/provider.js').then(m=>m.discoverServer()));
await page.route('**/api/agents',async r=>{
  const request=r.request().postDataJSON();
  assert.ok(!('instruction' in request));
  assert.ok(['facts','style','structure'].includes(request.agent));
  const good={category:'文意',severity:'check',title:'限定条件が失われています',explanation:'取材では対象を一部に限定しています。',quote:'すべてのお客様で効果を確認できました',source_id:request.input.transcript.find(s=>s.text.includes('一部のお客様で効果を確認できました。')).id,evidence:'一部のお客様で効果を確認できました。',suggestion:'一部のお客様で効果を確認できました'};
  const bad={...good,source_id:'T999'};
  const findings=request.agent==='facts'?[good,bad]:[];
  await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({findings})}}]})});
});
await page.locator('#back-input').click();
await page.locator('#settings-button').click();
await page.locator('#data-consent').check();
await page.getByRole('button',{name:'設定を適用',exact:true}).click();
await page.locator('#run-review').click();
await page.locator('#result-view').waitFor({state:'visible'});
assert.equal(await page.locator('#total-count').textContent(),'1');
assert.ok((await page.locator('#notice').textContent()).includes('1件の指摘'));
assert.equal(await page.evaluate(()=>Object.keys(localStorage).length),0);
await page.locator('#back-input').click();
await page.unroute('**/api/agents');
await page.route('**/api/agents',r=>r.fulfill({status:401,contentType:'application/json',body:'{}'}));
await page.locator('#run-review').click();
await page.locator('#notice.error').waitFor({state:'visible'});
assert.ok((await page.locator('#notice').textContent()).includes('運営者'));
assert.ok((await page.locator('#draft').inputValue()).includes('50%'));
assert.equal(await page.locator('#run-review').isEnabled(),true);
await page.locator('#settings-button').click();
await page.locator('#disconnect').click();
await page.locator('#draft').fill('');
await page.locator('#run-review').click();
assert.ok((await page.locator('#notice').textContent()).includes('初稿'));
await page.evaluate(()=>window.onbeforeunload=null);
page.on('dialog',d=>d.accept());
await page.locator('#load-sample').click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/angle-review-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
await page.locator('#run-review').click();
await page.locator('#result-view').waitFor({state:'visible'});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
await page.screenshot({path:'/tmp/angle-review-mobile-results.png',fullPage:true});
assert.deepEqual(errors,[]);
await browser.close();
console.log('Browser checks passed: review, adopt/undo/dismiss, export, AI response contract, invalid citations, API failure, input validation, WebMCP, mobile layout.');
