import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)('/opt/codex/runtimes/cua/lib/node_modules/playwright-core');const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],csp=[],calls=[];let connected=false;
 page.on('dialog',d=>d.accept());page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.text().includes('Content Security Policy'))csp.push(m.text());});
 await page.route('**/api/status',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({configured:connected,connection:connected?'not_checked':'missing_key',defaultModel:'google/gemini-2.5-flash'})}));
 await page.route('**/api/connection',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({configured:connected,connection:connected?'ready':'missing_key',defaultModel:'google/gemini-2.5-flash'})}));
 const fixture=id=>['facts','style','structure','final_check'].includes(id)?{findings:[]}:['writing','rewrite'].includes(id)?{summary:'取材から執筆',title:'業務改善の仕組み',article:'一部のお客様で効果を確認できました。'}:id==='research'?{summary:'調査',themes:['改善'],facts:[],gaps:[]}:id==='titles'?{summary:'見出し',titles:['改善の仕組み'],headings:['背景'],tags:['改善'],categories:['ビジネス']}:id==='social'?{summary:'投稿案',posts:[{platform:'X',text:'改善の仕組み ［記事URL］'}]}:{summary:'制作結果',content:'必要な確認をまとめました。',items:['確認する']};
 await page.route('**/api/agents',async r=>{const b=r.request().postDataJSON();calls.push(b);await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(fixture(b.agent))}}]})});});
 await page.goto('http://127.0.0.1:4173/');await page.locator('#nav-workflow').click();await page.locator('#workflow-run').click();assert.ok((await page.locator('#workflow-status').textContent()).includes('企画テーマ'));assert.equal(calls.length,0);
 await page.locator('#wf-topic').fill('業務改善の記事');await page.locator('#wf-audience').fill('経営者');await page.locator('#wf-goal').fill('取り組みの仕組みを伝える');await page.locator('#workflow-run').click();await page.waitForFunction(()=>document.getElementById('workflow-status').textContent.includes('準備がまだ'));assert.equal(calls.length,0);assert.equal(await page.locator('#wf-topic').inputValue(),'業務改善の記事');
 connected=true;await page.locator('#workflow-reconnect').click();await page.waitForFunction(()=>document.getElementById('workflow-status').textContent.includes('制作を利用できます'));
 await page.locator('#workflow-run').click();await page.locator('#settings-dialog').waitFor({state:'visible'});assert.equal(calls.length,0);await page.locator('#data-consent').check();await page.getByRole('button',{name:'設定を適用',exact:true}).click();await page.waitForFunction(()=>document.getElementById('workflow-phase').textContent==='取材待ち');assert.equal(calls.length,4);assert.ok(calls.every(c=>c.model==='google/gemini-2.5-flash'));
 await page.locator('#dashboard-search').fill('タイトルの案');assert.ok(await page.locator('[data-run-task="titles"]').isVisible());await page.locator('[data-run-task="titles"]').click();await page.waitForFunction(()=>document.getElementById('workflow-phase').textContent==='取材待ち');assert.equal(calls.length,4);
 await page.locator('#workflow-sample').click();calls.length=0;await page.locator('#dashboard-search').fill('質問を作って');assert.ok(await page.locator('[data-run-task="interview"]').isVisible());await page.locator('[data-run-task="interview"]').click();await page.waitForFunction(()=>document.getElementById('workflow-phase').textContent==='作業完了');assert.deepEqual(calls.map(c=>c.agent),['research','planning','coordination','interview']);assert.ok((await page.locator('#artifact-content').textContent()).includes('制作結果'));
 await page.locator('#dashboard-search').fill('SNSの投稿案をお願い');await page.locator('[data-run-task="social"]').click();await page.waitForFunction(()=>document.getElementById('workflow-phase').textContent==='作業完了'&&document.getElementById('artifact-title').textContent.includes('SNS'));assert.equal(calls.filter(c=>c.agent==='research').length,1);assert.ok(calls.some(c=>c.agent==='social'));assert.equal(await page.locator('#workflow-wordpress').isEnabled(),false);
 await page.locator('#nav-tasks').click();await page.locator('#task-search').fill('記事の制作を始める');assert.ok(await page.locator('[data-run-task="all"]').isVisible());await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('#task-search').isVisible(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);assert.deepEqual(csp,[]);assert.equal(await page.evaluate(()=>localStorage.length),0);console.log('Start verified: missing key, retry without reload, explicit consent auto-resume, owner model, task search and execution, prerequisite/HOTL gates, responsive search, no persistence.');
}finally{await browser.close();}
