import {test} from 'node:test';import assert from 'node:assert/strict';
import {handleWorkspace,workspaceConfigured,allowedEmail} from '../server/workspace.mjs';import {handleReminders} from '../server/reminders.mjs';import {validateSnapshot,paragraphEdit} from '../dist/project-snapshots.js';import {createRun} from '../dist/agents.js';
const env={SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_fixture',LOGIN_ALLOWED_EMAILS:'owner@company.test,@company.test'},origin='https://app.test';
const request=(path,body,cookie)=>new Request(origin+path,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});
test('workspace never permits anonymous document access, unsafe upstream origins or arbitrary email recipients',async()=>{assert.ok(workspaceConfigured(env));assert.equal(workspaceConfigured({...env,SUPABASE_URL:'https://attacker.test'}),false);assert.equal(allowedEmail('a@company.test.evil',env),false);assert.equal(allowedEmail('a@company.test',env),true);assert.equal((await handleWorkspace(request('/api/workspace/projects'),env)).status,401);assert.equal((await handleWorkspace(request('/api/auth/code',{email:'a@evil.test'}),env)).status,403);const unsafe=new Request(origin+'/api/auth/code',{method:'POST',headers:{Origin:'https://evil.test'},body:'{}'});assert.equal((await handleWorkspace(unsafe,env)).status,403);});
test('OTP verification uses secure HttpOnly cookies and never returns access or refresh tokens to client JS',async()=>{const previous=globalThis.fetch;globalThis.fetch=async(url,options)=>{assert.equal(url,env.SUPABASE_URL+'/auth/v1/verify');assert.equal(JSON.parse(options.body).type,'email');return Response.json({access_token:'server-access-fixture',refresh_token:'server-refresh-fixture',expires_in:3600,user:{id:'user',email:'owner@company.test'}});};try{const r=await handleWorkspace(request('/api/auth/verify',{email:'owner@company.test',code:'123456'}),env);assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');assert.ok(cookie.includes('HttpOnly'));assert.ok(cookie.includes('Secure'));assert.ok(cookie.includes('SameSite=Strict'));const data=await r.text();assert.equal(data.includes('server-access-fixture'),false);assert.equal(data.includes('server-refresh-fixture'),false);}finally{globalThis.fetch=previous;}});
test('saving uses verified user token, reports optimistic conflicts and rejects credential-like material',async()=>{const previous=globalThis.fetch;let writes=0;globalThis.fetch=async(url,options)=>{if(url.endsWith('/auth/v1/user'))return Response.json({id:'user',email:'owner@company.test',email_confirmed_at:'now'});writes++;assert.equal(options.headers.Authorization,'Bearer signed-fixture');return Response.json({code:'40001'},{status:409});};try{const body={id:null,revision:0,snapshot:{version:1,input:{topic:'企画'}},details:{}};let r=await handleWorkspace(request('/api/workspace/save',body,'__Host-angle_access=signed-fixture'),env);assert.equal(r.status,409);assert.equal((await r.json()).error,'save_conflict');r=await handleWorkspace(request('/api/workspace/save',{...body,snapshot:{key:'sk-proj-'+ 'a'.repeat(40)}},'__Host-angle_access=signed-fixture'),env);assert.equal(r.status,422);assert.equal(writes,1);}finally{globalThis.fetch=previous;}});
test('restoring a snapshot never restores approvals or trusts unknown workflow stages; paragraph edit changes only chosen text',()=>{const input={topic:'企画',audience:'編集者',goal:'説明',media:'ビジネスメディア',targetLength:1500,sources:'',rules:'',transcript:'取材',metrics:'',webSearch:false};const run=createRun(input);run.approvals={publication:{hash:'untrusted'}};assert.deepEqual(validateSnapshot({version:1,input,run}).run.approvals,{});run.agents[0].id='unknown';assert.throws(()=>validateSnapshot({version:1,input,run}));assert.equal(paragraphEdit('最初の段落。\n\n次の段落。',1,'変更した段落。'),'最初の段落。\n\n変更した段落。');assert.throws(()=>paragraphEdit('文章',5,'変更'));});
test('background reminder route rejects unsigned requests and remains unavailable without owner-managed mail settings',async()=>{assert.equal((await handleReminders(request('/api/reminders'),env)).status,403);const r=await handleReminders(new Request(origin+'/api/reminders',{headers:{Authorization:'Bearer fixture'}}),{...env,CRON_SECRET:'fixture'});assert.deepEqual(await r.json(),{available:false});});
test('expired or unavailable authentication cannot prevent clearing browser credentials',async()=>{
 const previous=globalThis.fetch;globalThis.fetch=async()=>{throw Error('offline');};try{
  for(const cookie of [undefined,'__Host-angle_access=expired; __Host-angle_refresh=fixture']){const r=await handleWorkspace(request('/api/auth/logout',{},cookie),env);assert.equal(r.status,200);assert.equal(r.headers.getSetCookie().length,2);for(const value of r.headers.getSetCookie())assert.ok(value.includes('Max-Age=0'));}
  const r=await handleWorkspace(request('/api/auth/status',undefined,'__Host-angle_access=fixture'),env);assert.equal(r.status,503);assert.deepEqual(await r.json(),{error:'workspace_unavailable'});
 }finally{globalThis.fetch=previous;}
});
