import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const require=createRequire(import.meta.url);const {chromium}=require('playwright-core');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
await context.addInitScript(()=>{window.deliveredNotices=[];class FakeNotification{static permission='granted';static async requestPermission(){return 'granted';}constructor(title,options){window.deliveredNotices.push({title,...options});}close(){}}Object.defineProperty(window,'Notification',{value:FakeNotification});});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
let calls=0,risk=true;
const article='一部のお客様で効果を確認できました。';
function fixture(id){
  if(['facts','style','structure','final_check'].includes(id))return {findings:id==='final_check'&&risk?[{category:'文意',severity:'check',title:'不正な根拠',explanation:'検証できない根拠',quote:article,source_id:'T999',evidence:'架空',suggestion:''},{category:'文意',severity:'check',title:'限定条件の確認',explanation:'限定条件を保ちます',quote:article,source_id:'T4',evidence:article,suggestion:'一部の顧客で効果を確認できました。'}]:[]};
  if(['writing','rewrite'].includes(id))return {summary:'取材に基づく原稿',title:'改善を続ける仕組み',article};
  if(id==='research')return {summary:'調査結果',themes:['継続的な改善'],facts:[],gaps:[]};
  if(id==='titles')return {summary:'タイトル提案',titles:['改善を続ける仕組み'],headings:['改善の背景'],tags:['業務改善'],categories:['ビジネス']};
  if(id==='social')return {summary:'投稿下書き',posts:[{platform:'X',text:'改善を続ける仕組み ［記事URL］'}]};
  return {summary:'専門エージェントの提案',content:'確認事項をまとめた下書きです。',items:['公開前に確認する']};
}
await page.route('**/api/agents',async r=>{calls++;const body=r.request().postDataJSON();await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({model:body.model,choices:[{finish_reason:'stop',message:{content:JSON.stringify(fixture(body.agent))}}],usage:{prompt_tokens:100,completion_tokens:200,cost:0.001}})});});
await page.route('**/api/{status,connection}',r=>r.fulfill({json:{configured:true,connection:'ready',defaultModel:'openai/gpt-4.1-mini'}}));
await page.goto('http://127.0.0.1:4173/');
await page.locator('#enable-notifications').click();
await page.locator('#nav-workflow').click();
await page.locator('#workflow-sample').evaluate(el=>{for(let parent=el.parentElement;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true;});await page.locator('#workflow-sample').click();
await page.screenshot({path:'/tmp/angle-workflow-input.png',fullPage:true});
await page.locator('#workflow-settings').click();
await page.locator('#data-classification').selectOption('restricted');
await page.locator('#data-consent').check();
await page.getByRole('button',{name:'設定を適用',exact:true}).click();
await page.locator('#workflow-run').click();
// The refusal follows the asynchronous connection check, so wait for it instead of reading immediately.
await page.waitForFunction(()=>document.getElementById('workflow-status').textContent.includes('送信できません'));
assert.equal(calls,0);
await page.locator('#workflow-settings').click();await page.locator('#data-classification').selectOption('internal');await page.getByRole('button',{name:'設定を適用',exact:true}).click();
await page.locator('#wf-sources').fill('架空の資料。担当者の連絡先 sample@example.com。');
await page.locator('#workflow-preview').click();
assert.ok(!(await page.locator('#privacy-preview').textContent()).includes('sample@example.com'));
await page.locator('[data-close="privacy-dialog"]').click();
await page.locator('#workflow-run').click();
await page.locator('#approval-panel').waitFor({state:'visible'});
await page.waitForFunction(()=>document.getElementById('workflow-phase').textContent==='人の確認待ち');
// The rewrite step is applied locally from verified findings (no AI call), so 10 specialists run before review.
assert.equal(calls,10);
assert.equal(await page.locator('#notification-badge').textContent(),'1');
assert.equal(await page.evaluate(()=>window.deliveredNotices.length),1);
assert.ok(!(await page.evaluate(()=>JSON.stringify(window.deliveredNotices))).includes(article));
await page.locator('#nav-dashboard').click();
assert.equal(await page.locator('#approval-count').textContent(),'1件');
assert.equal(await page.locator('#legend-done').textContent(),'11');
await page.screenshot({path:'/tmp/angle-dashboard-risk.png',fullPage:true});
await page.locator('#notification-bell').click();
await page.locator('[data-notice="0"]').click();
assert.equal(await page.locator('#approval-panel').isVisible(),true);
assert.equal(await page.locator('#notification-badge').isVisible(),false);
assert.equal(await page.locator('#workflow-wordpress').isEnabled(),false);
await page.locator('#approval-reason').fill('最終照合の除外された指摘と取材の根拠を確認し、再開を承認しました');
await page.locator('#approval-submit').click();
await page.waitForFunction(()=>document.getElementById('workflow-phase').textContent==='実績待ち');
assert.equal(calls,14);
assert.equal(await page.evaluate(()=>window.deliveredNotices.length),3);
assert.equal(await page.locator('#workflow-wordpress').isEnabled(),false);
await page.locator('#workflow-approve-publication').click();
await page.locator('#approval-reason').fill('原稿と引用の根拠、タイトル、SNS案、素材の権利を確認しました');
await page.locator('#approval-submit').click();
assert.equal(await page.locator('#workflow-wordpress').isEnabled(),true);
let promise=page.waitForEvent('download');await page.locator('#workflow-wordpress').evaluate(el=>{for(let parent=el.parentElement;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true;});await page.locator('#workflow-wordpress').click();let download=await promise;
assert.ok((await fs.readFile(await download.path(),'utf8')).includes(article));
promise=page.waitForEvent('download');await page.locator('#workflow-bundle').evaluate(el=>{for(let parent=el.parentElement;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true;});await page.locator('#workflow-bundle').click();download=await promise;
const record=JSON.parse(await fs.readFile(await download.path(),'utf8'));
assert.equal(record.status,'awaiting_metrics');assert.ok(record.approvals.publication);assert.ok(record.audit.length>20);
assert.ok(!JSON.stringify(record).includes('sk-or-v1-local-dummy'));assert.ok(!JSON.stringify(record).includes('sample@example.com'));
await page.locator('#brief-details > summary').click();await page.locator('#metrics-details > summary').click();await page.locator('#wf-metrics').fill('PV1000、問い合わせ2件。計測期間は公開後7日。');await page.locator('#workflow-run').click();
await page.waitForFunction(()=>document.getElementById('workflow-phase').textContent==='完了');
assert.equal(calls,15);
await page.locator('[data-progress-agent="archive"]').click();await page.locator('[data-agent="analytics"]').click();
await page.screenshot({path:'/tmp/angle-workflow-results.png',fullPage:true});
await page.locator('#workflow-review').click();await page.locator('#result-view').waitFor({state:'visible'});
assert.ok((await page.locator('#article-content').textContent()).includes(article));
await page.getByRole('button',{name:'修正を採用',exact:true}).click();
await page.locator('#nav-workflow').click();
assert.equal(await page.locator('#workflow-wordpress').isEnabled(),false);
assert.equal(await page.locator('#workflow-approve-publication').isEnabled(),false);
risk=false;
await page.locator('#workflow-run').click();
await page.waitForFunction(()=>document.getElementById('workflow-phase').textContent==='完了');
assert.equal(calls,21);
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:'/tmp/angle-workflow-mobile.png',fullPage:true});
await page.locator('.utility-menu > summary').click();await page.locator('#workflow-clear').click();
assert.equal(await page.locator('#wf-topic').inputValue(),'');
assert.equal(await page.locator('#wf-completed').textContent(),'0 / 17');
assert.equal(await page.locator('#notification-badge').isVisible(),false);
assert.equal(await page.evaluate(()=>localStorage.length),0);
assert.deepEqual(errors,[]);
await browser.close();console.log('Workflow browser checks passed: restricted-data block, masked preview, HOTL pause/resume, publication approval, complete exports, metrics resume, no secret persistence, mobile, clear.');
