import {allowedEmail} from './workspace.mjs';
// Compares digests so the comparison time does not reveal how much of the secret matched.
async function sameSecret(given,expected){const enc=new TextEncoder(),[a,b]=await Promise.all([given,expected].map(v=>crypto.subtle.digest('SHA-256',enc.encode(v))));const x=new Uint8Array(a),y=new Uint8Array(b);let diff=0;for(let i=0;i<x.length;i++)diff|=x[i]^y[i];return diff===0;}
const validId=s=>typeof s==='string'&&/^[a-f0-9-]{36}$/i.test(s);
export async function handleReminders(request,env){if(new URL(request.url).pathname!=='/api/reminders')return null;const json=(body,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});if(!env.CRON_SECRET||!await sameSecret(request.headers.get('Authorization')||'',`Bearer ${env.CRON_SECRET}`))return json({error:'access_denied'},403);if(request.method==='GET')return json({available:!!(env.RESEND_API_KEY&&env.NOTIFICATION_FROM&&env.LOGIN_ALLOWED_EMAILS)});if(request.method!=='POST')return json({error:'method_not_allowed'},405);if(!env.RESEND_API_KEY||!env.NOTIFICATION_FROM||!env.LOGIN_ALLOWED_EMAILS)return json({error:'mail_unavailable'},503);
 try{let size=0,text='';const reader=request.body.getReader(),decoder=new TextDecoder();while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>30000){await reader.cancel();return json({error:'too_large'},413);}text+=decoder.decode(value,{stream:true});}const notices=JSON.parse(text);if(!Array.isArray(notices)||notices.length>50||notices.some(n=>!validId(n.id)||!allowedEmail(n.recipient,env)||!['review','deadline'].includes(n.kind)||Object.keys(n).some(k=>!['id','recipient','kind'].includes(k))))return json({error:'invalid_notices'},422);const sent=[];
 for(const n of notices){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json','Idempotency-Key':'angle-notice-'+n.id},body:JSON.stringify({from:env.NOTIFICATION_FROM,to:[n.recipient],subject:n.kind==='review'?'ANGLE Review：記事の確認をお願いします':'ANGLE Review：記事の期限が近づいています',text:'担当する記事に確認が必要です。会社のメールでログインし、保存した記事からご確認ください。\nhttps://agents-of-edit.vercel.app/'}),signal:AbortSignal.timeout(10000),redirect:'error'});if(r.ok)sent.push(n.id);}return json({sent});
 }catch{return json({error:'reminder_failed'},503);}
}
